### ISSUE TITLE
" ... is vulnerable to a ... vulnerability"

### ISSUE THREAD

**Issue by theall38103** [distributedweaknessfiling/DWF-Database-Artifacts#8]
JSON-file-format.md currently says that the description should use the following format :

[Vendor name] [product name] version [version info] is vulnerable to a [flaw type] in the [component] resulting [some impact]. 

A product can be "vulnerable to attack", "affected by a vulnerability", or simply "have a vulnerability". But "is vulnerable to a vulnerability" makes little sense to me. I suggest replacing "vulnerable to" with "affected by" or something similar.

**Comment by kurtseifried** [comment]
Uh? No, they would put something like "Cross-Site scripting" or "CWE-79", not "a vulnerability".

**Comment by theall38103** [comment]
You mean "is vulnerable to a cross-site scripting attack"? 

CVE-2016-1000002.json has "vulnerable to an information disclosure vulnerability".

**Comment by kurtseifried** [comment]
Yup, at this time we don't know what the exact flaw is, again, sometimes rules are made to be broken =). But we can easily verify/confirm the flaw, so it needs a CVE.

**Comment by theall38103** [comment]
To be clear, my point is not whether a CVE is needed, only in the phrasing of descriptions generally.

**Comment by zmanion** [comment]
+1 for trying to avoid "vulnerable to vulnerability."
contains a...
vulnerable to an X attack...
vulnerable to CWE...
is affected by...
allows...

Understanding that titles will vary, and that's OK, but we can provide some guidance.

**Comment by sbunify** [comment]
The "description" is MANDATORY for a DWF entry to be created. But the detailed phrasing of the description SHOULD be in the format of.
If I understand @kurtseifried correctly, then the given format example is just a "default" suggestion, but other/similar phrasing would fit as well. So nothing forced into a corset.
And as @theall38103 suggests, I may also often draft descriptions in the sort of "is affected by" instead of "is vulnerable to"...
